#!/usr/bin/env php
<?php

ini_set('display_errors', 'stderr');
defined('YII_DEBUG') or define('YII_DEBUG', \getenv('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', \getenv('YII_ENV'));
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$relay = new \Spiral\Goridge\StreamRelay(STDIN, STDOUT);
$psr7 = new \Spiral\RoadRunner\PSR7Client(new \Spiral\RoadRunner\Worker($relay));

$config = require_once __DIR__ . '/config/web.php';

$application = (new \yii\Psr7\web\Application($config));

// Handle each HTTP request from RoadRunner
while ($request = $psr7->acceptRequest()) {
    try {
        $response = \Ajgarlag\Psr15\Dispatcher\Pipe::create([
            new \Middlewares\Uuid,
            new \Middlewares\ResponseTime
        ])->process($request, $application);

        $psr7->respond($response);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }

    if ($application->clean()) {
        $psr7->getWorker()->stop();
        return;
    }
}